version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5444:5432'
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./api:/wrookies-api
    ports:
      - "3001:3001"
    depends_on:
      - db
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api