default: &default
  adapter: postgresql
  encoding: unicode
  username: wrookies_user
  password: myspecialpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db

development:
  <<: *default
  database: wrookies_development

test:
  <<: *default
  database: wrookies_test

production:
  <<: *default
  host: db
  port: 5432
  database: wrookies
  username: <%= ENV['WROOKIES_DATABASE_USERNAME'] %>
  password: <%= ENV['WROOKIES_DATABASE_PASSWORD'] %>